# Generated by Django 5.0.2 on 2024-07-22 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team_leader',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'team_leader'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
